# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: omp_rpc/omp_rpc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'omp_rpc/omp_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15omp_rpc/omp_rpc.proto\x12\nomp.rpc.v1\"I\n\x07\x43ommand\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cpayload_json\x18\x03 \x01(\x0c\x12\x0e\n\x06has_id\x18\x04 \x01(\x08\"*\n\x04Push\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\x0c\"`\n\x0b\x43lientFrame\x12&\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x13.omp.rpc.v1.CommandH\x00\x12 \n\x04push\x18\x02 \x01(\x0b\x32\x10.omp.rpc.v1.PushH\x00\x42\x07\n\x05\x66rame\"<\n\x05Ready\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x19\n\x11max_message_bytes\x18\x02 \x01(\x04\"\xaf\x01\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06has_id\x18\x02 \x01(\x08\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x11\n\tdata_json\x18\x05 \x01(\x0c\x12\x10\n\x08has_data\x18\x06 \x01(\x08\x12\r\n\x05\x65rror\x18\x07 \x01(\t\x12\x0c\n\x04\x63ode\x18\x08 \x01(\t\x12\x11\n\thas_error\x18\t \x01(\x08\x12\x10\n\x08has_code\x18\n \x01(\x08\"\x86\x01\n\x0bServerFrame\x12\"\n\x05ready\x18\x01 \x01(\x0b\x32\x11.omp.rpc.v1.ReadyH\x00\x12(\n\x08response\x18\x02 \x01(\x0b\x32\x14.omp.rpc.v1.ResponseH\x00\x12 \n\x04push\x18\x03 \x01(\x0b\x32\x10.omp.rpc.v1.PushH\x00\x42\x07\n\x05\x66rame2O\n\x0c\x41gentService\x12?\n\x07\x43onnect\x12\x17.omp.rpc.v1.ClientFrame\x1a\x17.omp.rpc.v1.ServerFrame(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omp_rpc.omp_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=37
  _globals['_COMMAND']._serialized_end=110
  _globals['_PUSH']._serialized_start=112
  _globals['_PUSH']._serialized_end=154
  _globals['_CLIENTFRAME']._serialized_start=156
  _globals['_CLIENTFRAME']._serialized_end=252
  _globals['_READY']._serialized_start=254
  _globals['_READY']._serialized_end=314
  _globals['_RESPONSE']._serialized_start=317
  _globals['_RESPONSE']._serialized_end=492
  _globals['_SERVERFRAME']._serialized_start=495
  _globals['_SERVERFRAME']._serialized_end=629
  _globals['_AGENTSERVICE']._serialized_start=631
  _globals['_AGENTSERVICE']._serialized_end=710
# @@protoc_insertion_point(module_scope)
